spring.application.name=project Management System - PROD

spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=iSFGgCBENZtrGhkdzjhDgGLjtLIuwRBZ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

app.frontend.url=https://project-management-ivory.vercel.app
